spring:
  datasource:
    url: ${VAULT_DB_URL:jdbc:postgresql://localhost:5431/payment-gateway-vault-DB}

server:
  port: 9040

vault:
  master-key: 36EzFVZlpE9JqaoMByKKBhVBEDDTe41kL8XseWvtaK0=

resilience4j:
  thread-pool-bulkhead:
    instances:
      vault-card-processor:
        core-thread-pool-size: 5
        max-thread-pool-size: 10
        queue-capacity: 20